# Generated by Django 5.0.1 on 2024-03-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=50)),
                ("activity_desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Addon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addon", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Desination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("des_name", models.CharField(max_length=30)),
                ("cover_image", models.ImageField(blank=True, upload_to="img/")),
                ("desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_image", models.ImageField(blank=True, upload_to="img/")),
                ("name", models.CharField(max_length=30)),
                ("desc", models.TextField()),
                (
                    "dest_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.desination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_image", models.ImageField(blank=True, upload_to="img/")),
                ("description", models.CharField(max_length=1000)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("cruiser_price", models.IntegerField()),
                ("van_price", models.IntegerField()),
                (
                    "activities",
                    models.ManyToManyField(
                        blank=True, default=None, to="main.activity"
                    ),
                ),
                (
                    "addons",
                    models.ManyToManyField(blank=True, default=None, to="main.addon"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination",
                        to="main.desination",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package",
                        to="main.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("identity_number", models.CharField(max_length=12)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "naitionality",
                    models.CharField(
                        choices=[
                            ("RESIDENT", "Resident"),
                            ("NON-RESIDENT", "Non-Resident"),
                        ],
                        default="Resident",
                        max_length=30,
                    ),
                ),
                ("number", models.PositiveBigIntegerField(default=1)),
                ("price", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("book_status", models.BooleanField(default=False)),
                ("reject_status", models.BooleanField(default=False)),
                ("reject_reason", models.TextField(blank=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.package"
                    ),
                ),
            ],
        ),
    ]
