# Generated by Django 5.0.1 on 2024-03-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_package_destination"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days",
                    models.IntegerField(
                        choices=[
                            ("DAY 1", 1),
                            ("DAY 2", 2),
                            ("DAY 3", 3),
                            ("DAY 4", 4),
                            ("DAY 5", 5),
                            ("DAY 6", 6),
                        ],
                        default=1,
                        max_length=30,
                    ),
                ),
                ("activities", models.ManyToManyField(blank=True, to="main.activity")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="main.package",
                    ),
                ),
            ],
        ),
    ]
