# Generated by Django 5.0.1 on 2024-03-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tourschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excluded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addon", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="tourschedule",
            name="days",
            field=models.IntegerField(
                choices=[
                    (1, "DAY 1"),
                    (2, "DAY 2"),
                    (3, "DAY 3"),
                    (4, "DAY 4"),
                    (5, "DAY 5"),
                    (6, "DAY 6"),
                ],
                default=1,
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="excluded",
            field=models.ManyToManyField(blank=True, default=None, to="main.excluded"),
        ),
    ]
